#include "project_generator.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <array>
#include <cstdio>
#include <windows.h>

namespace Solar::Studio {

    namespace fs = std::filesystem;

    std::string ProjectGenerator::AutoDetectMSBuild() {
        const std::vector<std::string> candidates = {
            "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\MSBuild\\Current\\Bin\\MSBuild.exe",
            "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe"
        };

        for (const auto& path : candidates) {
            std::error_code ec;
            if (fs::exists(path, ec)) {
                return path;
            }
        }

        // Fall back to MSBuild in PATH
        return "MSBuild.exe";
    }

    bool ProjectGenerator::GenerateProjectFiles(const ProjectConfig& config, std::string& outErrorMessage) {
        try {
            fs::create_directories(config.outputDir);

            // 1. Generate main.cpp
            std::string mainCppPath = (fs::path(config.outputDir) / "main.cpp").string();
            std::ofstream mainFile(mainCppPath);
            if (!mainFile.is_open()) {
                outErrorMessage = "Failed to open " + mainCppPath + " for writing.";
                return false;
            }

            if (config.outputType == TargetOutputType::StandaloneExe) {
                mainFile << R"(// ==============================================================================
// )" << config.projectName << R"( - Generated by Solar Studio [BETA v0.1.2]
// C++20 / DirectX 11 Standalone Architecture
// ==============================================================================
#include <solar/solar.hpp>
#include <windows.h>
#include <d3d11.h>
#include <tchar.h>

#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "dwmapi.lib")
#pragma comment(lib, "winmm.lib")

static ID3D11Device*            g_pd3dDevice = nullptr;
static ID3D11DeviceContext*     g_pd3dDeviceContext = nullptr;
static IDXGISwapChain*          g_pSwapChain = nullptr;
static ID3D11RenderTargetView*  g_mainRenderTargetView = nullptr;

bool CreateDeviceD3D(HWND hWnd);
void CleanupDeviceD3D();
void CreateRenderTarget();
void CleanupRenderTarget();
LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE, LPSTR, int) {
    WNDCLASSEXW wc = { sizeof(wc), CS_CLASSDC, WndProc, 0L, 0L, hInstance, nullptr, nullptr, nullptr, nullptr, L"SolarCustomWindowClass", nullptr };
    ::RegisterClassExW(&wc);
    HWND hwnd = ::CreateWindowW(wc.lpszClassName, L")" << config.projectName << R"(", WS_OVERLAPPEDWINDOW, 100, 100, 
                                )" << static_cast<int>(config.windowWidth) << R"(, )" << static_cast<int>(config.windowHeight) << R"(, nullptr, nullptr, wc.hInstance, nullptr);

    if (!CreateDeviceD3D(hwnd)) {
        CleanupDeviceD3D();
        ::UnregisterClassW(wc.lpszClassName, wc.hInstance);
        return 1;
    }

    ::ShowWindow(hwnd, SW_SHOWDEFAULT);
    ::UpdateWindow(hwnd);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;

    ImGui_ImplWin32_Init(hwnd);
    ImGui_ImplDX11_Init(g_pd3dDevice, g_pd3dDeviceContext);

    // Initialize Solar Framework with Custom Settings
    Solar::SetMode(Solar::FrameworkMode::External);
    Solar::Initialize();
    
    // Apply Studio Visual Calibration
    auto& theme = Solar::ThemeManager::Get();
    Solar::Palette customPal = theme.GetPalette();
    customPal.Accent = Solar::Color()" << config.accentColor[0] << "f, " << config.accentColor[1] << "f, " << config.accentColor[2] << "f, " << config.accentColor[3] << R"(f);
    customPal.Card = Solar::Color()" << config.cardColor[0] << "f, " << config.cardColor[1] << "f, " << config.cardColor[2] << "f, " << config.cardColor[3] << R"(f);
    theme.SetCustomPalette(customPal);

    auto& style = theme.GetStyle();
    style.WindowRounding = )" << config.borderRounding << R"(f;
    style.CardRounding = )" << config.borderRounding << R"(f;
    style.EnableGlow = )" << (config.enableGlow ? "true" : "false") << R"(;

    bool bRunning = true;
    while (bRunning) {
        MSG msg;
        while (::PeekMessage(&msg, nullptr, 0U, 0U, PM_REMOVE)) {
            ::TranslateMessage(&msg);
            ::DispatchMessage(&msg);
            if (msg.message == WM_QUIT) bRunning = false;
        }
        if (!bRunning) break;

        ImGui_ImplDX11_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();
        Solar::NewFrame();

        // Render Main Window
        bool open = true;
        if (Solar::Widgets::BeginWindow("##MainWindow", &open, ImVec2()" << config.windowWidth << ", " << config.windowHeight << R"())) {
            Solar::Widgets::RenderTitlebar(")" << config.windowTitle << R"(", ")" << config.windowSubtitle << R"(", &open);
            
            Solar::Widgets::BeginSidebar(220.0f);
            Solar::Widgets::SidebarCategory("NAVIGATION");
            static int selectedTab = 0;
            Solar::Widgets::SidebarTab("Dashboard", Solar::IconType::Crosshair, 0, &selectedTab);
            Solar::Widgets::SidebarTab("Telemetry", Solar::IconType::Sliders, 1, &selectedTab);
            Solar::Widgets::SidebarTab("Settings", Solar::IconType::Shield, 2, &selectedTab);
            Solar::Widgets::EndSidebar();

            ImGui::SameLine(0, 16.0f);
            ImGui::BeginGroup();
            
            if (Solar::Widgets::BeginCard("##MainCard", "Core Operations", Solar::IconType::Sliders, ImVec2(0, 480.0f))) {
                static bool featureA = true;
                static float sliderVal = 65.0f;
                Solar::Widgets::Toggle("Industrial Dynamic Pipeline", &featureA, "Enhanced throughput module");
                Solar::Widgets::SliderFloat("Processing Frequency", &sliderVal, 10.0f, 100.0f, "%.1f", "Hz");
                
                Solar::Widgets::Separator();
                if (Solar::Widgets::Button("Execute Synchronous Pass", ImVec2(0, 38))) {
                    Solar::Audio::PlayClick();
                    Solar::Notify::Success("Pipeline Executed", "DirectX 11 state verified and active.");
                }
                Solar::Widgets::EndCard();
            }
            
            ImGui::EndGroup();
            Solar::Widgets::EndWindow();
        }

        ImGui::Render();
        const float clear_color[4] = { 0.05f, 0.06f, 0.08f, 1.00f };
        g_pd3dDeviceContext->OMSetRenderTargets(1, &g_mainRenderTargetView, nullptr);
        g_pd3dDeviceContext->ClearRenderTargetView(g_mainRenderTargetView, clear_color);
        ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
        g_pSwapChain->Present(1, 0);
    }

    Solar::Shutdown();
    ImGui_ImplDX11_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();

    CleanupDeviceD3D();
    ::DestroyWindow(hwnd);
    ::UnregisterClassW(wc.lpszClassName, wc.hInstance);
    return 0;
}

bool CreateDeviceD3D(HWND hWnd) {
    DXGI_SWAP_CHAIN_DESC sd = {};
    sd.BufferCount = 2;
    sd.BufferDesc.Width = 0;
    sd.BufferDesc.Height = 0;
    sd.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferDesc.RefreshRate.Numerator = 60;
    sd.BufferDesc.RefreshRate.Denominator = 1;
    sd.Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH;
    sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.OutputWindow = hWnd;
    sd.SampleDesc.Count = 1;
    sd.SampleDesc.Quality = 0;
    sd.Windowed = TRUE;
    sd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;

    UINT createDeviceFlags = 0;
    D3D_FEATURE_LEVEL featureLevel;
    const D3D_FEATURE_LEVEL featureLevelArray[2] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0, };
    HRESULT res = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, createDeviceFlags, featureLevelArray, 2, D3D11_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice, &featureLevel, &g_pd3dDeviceContext);
    if (res != S_OK) return false;

    CreateRenderTarget();
    return true;
}

void CleanupDeviceD3D() {
    CleanupRenderTarget();
    if (g_pSwapChain) { g_pSwapChain->Release(); g_pSwapChain = nullptr; }
    if (g_pd3dDeviceContext) { g_pd3dDeviceContext->Release(); g_pd3dDeviceContext = nullptr; }
    if (g_pd3dDevice) { g_pd3dDevice->Release(); g_pd3dDevice = nullptr; }
}

void CreateRenderTarget() {
    ID3D11Texture2D* pBackBuffer;
    g_pSwapChain->GetBuffer(0, IID_PPV_ARGS(&pBackBuffer));
    g_pd3dDevice->CreateRenderTargetView(pBackBuffer, nullptr, &g_mainRenderTargetView);
    pBackBuffer->Release();
}

void CleanupRenderTarget() {
    if (g_mainRenderTargetView) { g_mainRenderTargetView->Release(); g_mainRenderTargetView = nullptr; }
}

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam)) return true;
    switch (msg) {
    case WM_SIZE:
        if (g_pd3dDevice != nullptr && wParam != SIZE_MINIMIZED) {
            CleanupRenderTarget();
            g_pSwapChain->ResizeBuffers(0, (UINT)LOWORD(lParam), (UINT)HIWORD(lParam), DXGI_FORMAT_UNKNOWN, 0);
            CreateRenderTarget();
        }
        return 0;
    case WM_DESTROY:
        ::PostQuitMessage(0);
        return 0;
    }
    return ::DefWindowProcW(hWnd, msg, wParam, lParam);
}
)";
            } else {
                // Internal DLL mode with SwapChain hook & Solar-Render isolation
                mainFile << R"(// ==============================================================================
// )" << config.projectName << R"( - Generated by Solar Studio [BETA v0.1.2]
// C++20 In-Process Hook DLL with UE4/UE5 Crash-Proof Solar-Render Pipeline
// ==============================================================================
#include <solar/solar.hpp>
#include <windows.h>
#include <d3d11.h>

static Solar::Hook::DX11StateGuard g_stateGuard;
static bool g_initialized = false;

// Custom In-Process Render Callback
void RenderInProcessOverlay(IDXGISwapChain* pSwapChain) {
    ID3D11Device* pDevice = nullptr;
    ID3D11DeviceContext* pContext = nullptr;

    if (FAILED(pSwapChain->GetDevice(__uuidof(ID3D11Device), (void**)&pDevice))) return;
    pDevice->GetImmediateContext(&pContext);

    if (!g_initialized) {
        Solar::SetMode(Solar::FrameworkMode::Internal);
        Solar::Initialize();
        
        // Apply Studio Visual Settings
        auto& theme = Solar::ThemeManager::Get();
        Solar::Palette customPal = theme.GetPalette();
        customPal.Accent = Solar::Color()" << config.accentColor[0] << "f, " << config.accentColor[1] << "f, " << config.accentColor[2] << "f, " << config.accentColor[3] << R"(f);
        theme.SetCustomPalette(customPal);
        theme.GetStyle().WindowRounding = )" << config.borderRounding << R"(f;
        theme.GetStyle().CardRounding = )" << config.borderRounding << R"(f;

        g_initialized = true;
    }

    // 1. Full 6-Stage DirectX 11 Pipeline Isolation (UE4/UE5 Crash Prevention)
    g_stateGuard.Capture(pContext);

    // 2. ImGui & Solar Rendering Pass
    Solar::NewFrame();
    bool open = true;
    if (Solar::Widgets::BeginWindow("##InternalHUD", &open, ImVec2()" << config.windowWidth << ", " << config.windowHeight << R"())) {
        Solar::Widgets::RenderTitlebar(")" << config.windowTitle << R"(", "In-Process Hook Mode", &open);
        if (Solar::Widgets::BeginCard("##InternalCard", "Telemetry & Overlay", Solar::IconType::Shield)) {
            static bool overlayActive = true;
            Solar::Widgets::Toggle("Active Telemetry HUD", &overlayActive);
            Solar::Widgets::EndCard();
        }
        Solar::Widgets::EndWindow();
    }

    // 3. Restore Full Pipeline State for UE4/UE5 Game Engine
    g_stateGuard.Restore();

    pContext->Release();
    pDevice->Release();
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved) {
    (void)hModule; (void)lpReserved;
    switch (ul_reason_for_call) {
    case DLL_PROCESS_ATTACH:
        ::DisableThreadLibraryCalls(hModule);
        break;
    case DLL_PROCESS_DETACH:
        if (g_initialized) Solar::Shutdown();
        break;
    }
    return TRUE;
}
)";
            }
            mainFile.close();

            // 2. Generate CMakeLists.txt
            std::string cmakePath = (fs::path(config.outputDir) / "CMakeLists.txt").string();
            std::ofstream cmakeFile(cmakePath);
            if (cmakeFile.is_open()) {
                cmakeFile << "cmake_minimum_required(VERSION 3.16)\n";
                cmakeFile << "project(" << config.projectName << " LANGUAGES CXX)\n\n";
                cmakeFile << "set(CMAKE_CXX_STANDARD 20)\n";
                cmakeFile << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";
                cmakeFile << "set(SOLAR_ROOT \"" << config.frameworkRootDir << "\")\n";
                cmakeFile << "include_directories(\"${SOLAR_ROOT}/include\" \"${SOLAR_ROOT}/vendor/imgui\" \"${SOLAR_ROOT}/vendor/imgui/backends\")\n";
                cmakeFile << "link_directories(\"${SOLAR_ROOT}/build/Release\")\n\n";
                if (config.outputType == TargetOutputType::StandaloneExe) {
                    cmakeFile << "add_executable(" << config.projectName << " WIN32 main.cpp)\n";
                } else {
                    cmakeFile << "add_library(" << config.projectName << " SHARED main.cpp)\n";
                }
                cmakeFile << "target_link_libraries(" << config.projectName << " PRIVATE solar_lib d3d11 dxgi dwmapi winmm shcore)\n";
                cmakeFile.close();
            }

            return true;
        } catch (const std::exception& e) {
            outErrorMessage = e.what();
            return false;
        }
    }

    bool ProjectGenerator::RunMSBuild(const ProjectConfig& config, const std::function<void(const std::string&)>& logCallback) {
        logCallback("[Solar Studio] Initializing MSBuild compiler pipeline...");
        logCallback("[Solar Studio] Project Target: " + config.projectName + (config.outputType == TargetOutputType::StandaloneExe ? " (.exe)" : " (.dll)"));
        logCallback("[Solar Studio] Output Directory: " + config.outputDir);

        std::string err;
        if (!GenerateProjectFiles(config, err)) {
            logCallback("[Solar Studio] ERROR: Failed to generate project files: " + err);
            return false;
        }
        logCallback("[Solar Studio] SUCCESS: C++20 files and CMake build scripts written.");

        // Build with CMake & MSBuild
        std::string buildDir = (fs::path(config.outputDir) / "build").string();
        fs::create_directories(buildDir);

        std::string cmakeConfigCmd = "cmake -B \"" + buildDir + "\" -S \"" + config.outputDir + "\" -DCMAKE_BUILD_TYPE=Release";
        logCallback("[Solar Studio] Running configuration: " + cmakeConfigCmd);

        FILE* pipe = _popen(cmakeConfigCmd.c_str(), "r");
        if (pipe) {
            char buffer[512];
            while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
                std::string line(buffer);
                while (!line.empty() && (line.back() == '\n' || line.back() == '\r')) line.pop_back();
                logCallback(line);
            }
            _pclose(pipe);
        }

        std::string cmakeBuildCmd = "cmake --build \"" + buildDir + "\" --config Release";
        logCallback("[Solar Studio] Running build compilation: " + cmakeBuildCmd);

        FILE* buildPipe = _popen(cmakeBuildCmd.c_str(), "r");
        if (buildPipe) {
            char buffer[512];
            while (fgets(buffer, sizeof(buffer), buildPipe) != nullptr) {
                std::string line(buffer);
                while (!line.empty() && (line.back() == '\n' || line.back() == '\r')) line.pop_back();
                logCallback(line);
            }
            int code = _pclose(buildPipe);
            if (code == 0) {
                logCallback("[Solar Studio] BUILD SUCCESSFUL! Target artifact ready in output folder.");
                return true;
            } else {
                logCallback("[Solar Studio] Build finished with code " + std::to_string(code));
                return false;
            }
        }

        return true;
    }

} // namespace Solar::Studio
